name: .NET Build and Pack

on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Create NuGet-package (.nupkg)
      run: dotnet pack --no-build --configuration Release --output ./nupkg


    - name: Publish to NuGet.org
      run: dotnet nuget push ./nupkg/*.nupkg --source https://nuget.org --skip-duplicate
